name: bangladesh_landmarks
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  

  http: ^1.1.0
  dio: ^5.4.0
  
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  image_picker: ^1.0.5
  image: ^4.1.3
  
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  device_info_plus: ^10.0.0
  
  provider: ^6.1.1
  
  shared_preferences: ^2.2.2
  

  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.0
  
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/